#!/bin/bash
set -euo pipefail
# Idempotent installer for the servingz watchdog + status page.
# Safe to re-run: never overwrites existing config.json or secrets/notify.json.
cd "$(dirname "$0")"

if ! command -v uv >/dev/null 2>&1 && [ ! -x "$HOME/.local/bin/uv" ]; then
  curl -LsSf https://astral.sh/uv/install.sh | sh
fi
export PATH="$HOME/.local/bin:$PATH"

if ! dpkg -l smartmontools >/dev/null 2>&1; then
  sudo apt-get install -y smartmontools
fi

mkdir -p state logs status secrets systemd
mkdir -p ../nodes

if [ ! -f config.json ]; then
  echo "ERROR: config.json missing — this should be committed to the repo, not generated by install.sh" >&2
  exit 1
fi

if [ ! -f secrets/notify.json ]; then
  echo "WARNING: secrets/notify.json missing. Creating a placeholder — edit it with your" >&2
  echo "ntfy topic and healthchecks.io ping URL before the watchdog can notify you." >&2
  cat > secrets/notify.json <<'EOF'
{
  "ntfy_topic": "",
  "healthchecks_ping_url": ""
}
EOF
  chmod 600 secrets/notify.json
fi

uv sync

sudo cp systemd/zorc-watchdog.service /etc/systemd/system/
sudo cp systemd/zorc-watchdog.timer /etc/systemd/system/
sudo cp systemd/zorc-status-server.service /etc/systemd/system/
sudo systemctl daemon-reload

sudo systemctl enable --now zorc-watchdog.timer
sudo systemctl enable --now zorc-status-server.service

echo "Installed. Check status with:"
echo "  systemctl status zorc-watchdog.timer zorc-status-server.service"
echo "  journalctl -u zorc-watchdog.service -n 50"
