tunnel: a8ceda0a-a10a-4924-8095-fb443319382d
credentials-file: /home/zman/.cloudflared/a8ceda0a-a10a-4924-8095-fb443319382d.json
ingress:
- hostname: coolify.zaindroid.me
  service: http://localhost:8000
- hostname: status.zaindroid.me
  service: http://localhost:9999
- hostname: hello.zaindroid.me
  service: https://localhost:443
  originRequest:
    noTLSVerify: true
- hostname: hello-staging.zaindroid.me
  service: https://localhost:443
  originRequest:
    noTLSVerify: true
- hostname: iht-cms.zaindroid.me
  service: https://localhost:443
  originRequest:
    noTLSVerify: true
- hostname: iht-search.zaindroid.me
  service: https://localhost:443
  originRequest:
    noTLSVerify: true
- hostname: iht-automations.zaindroid.me
  service: https://localhost:443
  originRequest:
    noTLSVerify: true
- hostname: iht-news.zaindroid.me
  service: https://localhost:443
  originRequest:
    noTLSVerify: true
- service: http_status:404
