tunnel: a8ceda0a-a10a-4924-8095-fb443319382d
credentials-file: /home/zman/.cloudflared/a8ceda0a-a10a-4924-8095-fb443319382d.json
ingress:
- hostname: coolify.zaindroid.me
  service: http://localhost:8000
- hostname: status.zaindroid.me
  service: http://localhost:9999
- hostname: mcp.zaindroid.me
  service: http://localhost:8081
- hostname: hello.zaindroid.me
  service: https://localhost:443
  originRequest:
    noTLSVerify: true
- hostname: hello-staging.zaindroid.me
  service: https://localhost:443
  originRequest:
    noTLSVerify: true
- hostname: iht-cms.zaindroid.me
  service: https://localhost:443
  originRequest:
    noTLSVerify: true
- hostname: iht-search.zaindroid.me
  service: https://localhost:443
  originRequest:
    noTLSVerify: true
- hostname: iht-automations.zaindroid.me
  service: https://localhost:443
  originRequest:
    noTLSVerify: true
- hostname: iht-news.zaindroid.me
  service: https://localhost:443
  originRequest:
    noTLSVerify: true
- hostname: ihtdaily.com
  service: https://localhost:443
  originRequest:
    noTLSVerify: true
- hostname: www.ihtdaily.com
  service: https://localhost:443
  originRequest:
    noTLSVerify: true
- hostname: hermes-sglang.zaindroid.me
  service: http://100.119.248.100:20000
- hostname: hermes.zaindroid.me
  service: https://localhost:443
  originRequest:
    noTLSVerify: true
- hostname: thor-platform.zaindroid.me
  service: https://localhost:443
  originRequest:
    noTLSVerify: true
- hostname: hermes4-api.zaindroid.me
  service: http://100.118.75.128:20000
- hostname: hermes4-rtx.zaindroid.me
  service: http://100.124.93.99:20000
- hostname: zbots.zaindroid.me
  service: https://localhost:443
  originRequest:
    noTLSVerify: true
- hostname: zbots-dev.zaindroid.me
  service: https://localhost:443
  originRequest:
    noTLSVerify: true
- hostname: loot-radar.zaindroid.me
  service: https://localhost:443
  originRequest:
    noTLSVerify: true
- service: http_status:404
